version: "3.7"
services:
  postgres:
    image: postgres:14
    platform: linux/arm64
    container_name: star-wars-database
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    networks:
      - net-services
  prueba-tecnica:
    depends_on: 
      - postgres
    build: ../PRUEBATECNICA/.
    container_name: prueba-tecnica-service
    image: prueba/prueba-tecnica-service
    restart: always
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    volumes:
      - ../PRUEBATECNICA:/usr/src/app
      - //usr/src/app/node_modules
      - //usr/src/app/.git
    networks:
      - net-services

# Docker Networks
networks:
  net-services:
    driver: bridge
